"""The Airflow dags resource: rendered modules, idempotent deploys."""

import logging
import pathlib

import pytest

from rekep import config
from rekep.airflow.service import Airflow, Dags

JOB = "job: passthrough\nschedule: '@daily'\nuri: rekep:///jobs/demo\n"
DAG = "uri: rekep:///dags/demo\nschedule: '@daily'\ntasks: [rekep:///jobs/demo]\n"


@pytest.fixture
def roots(tmp_path: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path]:
    """A jobs folder and a dags folder, the shape a checkout has."""
    config.clear()
    jobs, dags = tmp_path / "jobs", tmp_path / "dags"
    jobs.mkdir()
    dags.mkdir()
    (jobs / "demo.yaml").write_text(JOB, encoding="utf-8")
    (dags / "demo.yaml").write_text(DAG, encoding="utf-8")
    from rekep.job import load_all

    load_all(jobs)  # the tasks a dag references have to be resolvable
    yield jobs, dags
    config.clear()


@pytest.fixture
def dags_root(roots: tuple[pathlib.Path, pathlib.Path]) -> pathlib.Path:
    return roots[1]


def test_list_builds_dags_from_side_files(dags_root: pathlib.Path) -> None:
    (dag,) = Dags(dags_root).list()
    assert dag.dag_id() == "demo"
    assert dag.schedule == "@daily"
    assert dag.order() == ["demo"]


def test_rendered_module_names_the_side_file(dags_root: pathlib.Path) -> None:
    dags = Dags(dags_root)
    ((path, dag),) = dags.entries()
    module = dags.render(path, dag)
    assert 'globals()["demo"]' in module
    assert "demo.yaml" in module
    assert "Generated by rekep" in module


def test_a_branch_named_dag_still_finds_its_file(
    roots: tuple[pathlib.Path, pathlib.Path],
) -> None:
    """The file stem and the dag id deliberately differ once a dag renders
    its identity from the branch; the path is carried, never guessed back."""
    _, dags_root = roots
    (dags_root / "demo.yaml").write_text(
        "uri: rekep:///dags/demo_{{ suffix }}\ntasks: [rekep:///jobs/demo]\n".replace(
            "{{ suffix }}", "dev"
        ),
        encoding="utf-8",
    )
    dags = Dags(dags_root)
    ((path, dag),) = dags.entries()
    assert dag.dag_id() == "demo_dev"
    assert "demo.yaml" in dags.render(path, dag)


def test_deploy_writes_then_noops(
    roots: tuple[pathlib.Path, pathlib.Path],
    tmp_path: pathlib.Path,
    caplog: pytest.LogCaptureFixture,
) -> None:
    _, dags_root = roots
    dags_folder = tmp_path / "airflow-dags"
    deployed = Airflow.deploy_folder(dags_root, dags_folder=dags_folder)
    assert deployed == ["demo.py"]
    assert (dags_folder / "demo.py").is_file()

    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(dags_root, dags_folder=dags_folder)
    assert "module up to date, nothing to do" in caplog.text


def test_dry_run_writes_nothing(dags_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "airflow-dags"
    deployed = Airflow.deploy_folder(dags_root, dags_folder=dags_folder, dry_run=True)
    assert deployed == ["demo.py"]
    assert not dags_folder.exists()


def test_changed_side_file_rewrites_the_module(
    dags_root: pathlib.Path, tmp_path: pathlib.Path, caplog: pytest.LogCaptureFixture
) -> None:
    dags_folder = tmp_path / "airflow-dags"
    Airflow.deploy_folder(dags_root, dags_folder=dags_folder)
    (dags_folder / "demo.py").write_text("# stale by hand\n", encoding="utf-8")
    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(dags_root, dags_folder=dags_folder)
    assert "write" in caplog.text
    assert "Generated by rekep" in (dags_folder / "demo.py").read_text(encoding="utf-8")


def test_delete(dags_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "airflow-dags"
    service = Airflow(dags_root)
    service.deploy(dags_folder)
    (dag,) = service.dags.list()
    service.dags.delete(dag, dags_folder)
    assert not (dags_folder / "demo.py").exists()
    service.dags.delete(dag, dags_folder)  # absent is a logged no-op
