"""The Airflow dags resource: rendered modules, idempotent deploys."""

import logging
import pathlib

import pytest

from rekep.airflow.service import Airflow, Dags

FLOW = "flow: rekep.flows.Passthrough\nschedule: '@daily'\nname: demo\n"


@pytest.fixture
def flows_root(tmp_path: pathlib.Path) -> pathlib.Path:
    root = tmp_path / "flows"
    root.mkdir()
    (root / "demo.yaml").write_text(FLOW, encoding="utf-8")
    return root


def test_list_builds_dags_from_side_files(flows_root: pathlib.Path) -> None:
    (dag,) = Dags(flows_root).list()
    assert dag.name == "demo"
    assert dag.schedule == "@daily"
    assert [task.name for task in dag.tasks] == ["demo"]


def test_rendered_module_names_the_side_file(flows_root: pathlib.Path) -> None:
    dags = Dags(flows_root)
    (dag,) = dags.list()
    module = dags.render(dag)
    assert 'globals()["demo"]' in module
    assert "demo.yaml" in module
    assert "Generated by rekep" in module


def test_deploy_writes_then_noops(
    flows_root: pathlib.Path, tmp_path: pathlib.Path, caplog: pytest.LogCaptureFixture
) -> None:
    dags_folder = tmp_path / "dags"
    deployed = Airflow.deploy_folder(flows_root, dags_folder=dags_folder)
    assert deployed == ["demo.py"]
    assert (dags_folder / "demo.py").is_file()

    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(flows_root, dags_folder=dags_folder)
    assert "module up to date, nothing to do" in caplog.text


def test_dry_run_writes_nothing(flows_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "dags"
    deployed = Airflow.deploy_folder(flows_root, dags_folder=dags_folder, dry_run=True)
    assert deployed == ["demo.py"]
    assert not dags_folder.exists()


def test_changed_side_file_rewrites_the_module(
    flows_root: pathlib.Path, tmp_path: pathlib.Path, caplog: pytest.LogCaptureFixture
) -> None:
    dags_folder = tmp_path / "dags"
    Airflow.deploy_folder(flows_root, dags_folder=dags_folder)
    (dags_folder / "demo.py").write_text("# stale by hand\n", encoding="utf-8")
    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(flows_root, dags_folder=dags_folder)
    assert "write" in caplog.text
    assert "Generated by rekep" in (dags_folder / "demo.py").read_text(encoding="utf-8")


def test_delete(flows_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "dags"
    service = Airflow(flows_root)
    service.deploy(dags_folder)
    (dag,) = service.dags.list()
    service.dags.delete(dag, dags_folder)
    assert not (dags_folder / "demo.py").exists()
    service.dags.delete(dag, dags_folder)  # absent is a logged no-op
