"""The Airflow dags resource: rendered modules, idempotent deploys."""

import logging
import pathlib

import pytest

from rekep.airflow.service import Airflow, Dags

JOB = "job: rekep.job.Passthrough\nschedule: '@daily'\nname: demo\n"


@pytest.fixture
def jobs_root(tmp_path: pathlib.Path) -> pathlib.Path:
    root = tmp_path / "jobs"
    root.mkdir()
    (root / "demo.yaml").write_text(JOB, encoding="utf-8")
    return root


def test_list_builds_dags_from_side_files(jobs_root: pathlib.Path) -> None:
    (job,) = Dags(jobs_root).list()
    assert job.name == "demo"
    assert job.schedule == "@daily"


def test_rendered_module_names_the_side_file(jobs_root: pathlib.Path) -> None:
    dags = Dags(jobs_root)
    (job,) = dags.list()
    module = dags.render(job)
    assert 'globals()["demo"]' in module
    assert "demo.yaml" in module
    assert "Generated by rekep" in module


def test_deploy_writes_then_noops(
    jobs_root: pathlib.Path, tmp_path: pathlib.Path, caplog: pytest.LogCaptureFixture
) -> None:
    dags_folder = tmp_path / "dags"
    deployed = Airflow.deploy_folder(jobs_root, dags_folder=dags_folder)
    assert deployed == ["demo.py"]
    assert (dags_folder / "demo.py").is_file()

    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(jobs_root, dags_folder=dags_folder)
    assert "module up to date, nothing to do" in caplog.text


def test_dry_run_writes_nothing(jobs_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "dags"
    deployed = Airflow.deploy_folder(jobs_root, dags_folder=dags_folder, dry_run=True)
    assert deployed == ["demo.py"]
    assert not dags_folder.exists()


def test_changed_side_file_rewrites_the_module(
    jobs_root: pathlib.Path, tmp_path: pathlib.Path, caplog: pytest.LogCaptureFixture
) -> None:
    dags_folder = tmp_path / "dags"
    Airflow.deploy_folder(jobs_root, dags_folder=dags_folder)
    (dags_folder / "demo.py").write_text("# stale by hand\n", encoding="utf-8")
    with caplog.at_level(logging.INFO, logger="rekep.airflow"):
        Airflow.deploy_folder(jobs_root, dags_folder=dags_folder)
    assert "write" in caplog.text
    assert "Generated by rekep" in (dags_folder / "demo.py").read_text(encoding="utf-8")


def test_delete(jobs_root: pathlib.Path, tmp_path: pathlib.Path) -> None:
    dags_folder = tmp_path / "dags"
    service = Airflow(jobs_root)
    service.deploy(dags_folder)
    (job,) = service.dags.list()
    service.dags.delete(job, dags_folder)
    assert not (dags_folder / "demo.py").exists()
    service.dags.delete(job, dags_folder)  # absent is a logged no-op
