"""Fields: a dataclass is its own Arrow schema."""

from rekep.fields.arrow import merge_fields, merge_schemas
from rekep.fields.builder import FieldBuilder
from rekep.fields.classes import ClassBuilder
from rekep.fields.field import (
    DESCRIPTION,
    FIELD_ID,
    FIX,
    ICEBERG,
    NAME,
    NAMESPACE,
    PARTITION_KEY,
    PRIMARY_KEY,
    SORT_KEY,
    Field,
    FixedSizeListField,
    LargeListField,
    LargeListViewField,
    ListField,
    ListViewField,
    MapField,
    ProtocolMetadata,
    StructField,
    cast_batch,
    cast_reader,
    cast_table,
    scalar,
)

__all__ = [
    "DESCRIPTION",
    "FIELD_ID",
    "FIX",
    "ICEBERG",
    "NAME",
    "NAMESPACE",
    "PARTITION_KEY",
    "PRIMARY_KEY",
    "SORT_KEY",
    "ClassBuilder",
    "Field",
    "FieldBuilder",
    "ProtocolMetadata",
    "FixedSizeListField",
    "LargeListField",
    "LargeListViewField",
    "ListField",
    "ListViewField",
    "MapField",
    "StructField",
    "cast_batch",
    "cast_reader",
    "cast_table",
    "merge_fields",
    "merge_schemas",
    "scalar",
]
