"""Fields: a dataclass is its own Arrow schema."""

from rekep.fields.arrow import merge_fields, merge_schemas
from rekep.fields.builder import FieldBuilder
from rekep.fields.classes import ClassBuilder
from rekep.fields.field import (
    DESCRIPTION,
    DISPLAY,
    ENUM,
    FIELD_ID,
    FIX,
    ICEBERG,
    ITEM,
    NAME,
    NAMESPACE,
    PARTITION_KEY,
    PRIMARY_KEY,
    SORT_KEY,
    SORT_ORDER,
    BinaryField,
    DictionaryField,
    Field,
    FixedSizeListField,
    LargeListField,
    LargeListViewField,
    ListField,
    ListViewField,
    MapField,
    StructField,
    TimestampField,
    cast_batch,
    cast_reader,
    cast_table,
    scalar,
)
from rekep.fields.metadata import (
    ANY_VERSION,
    Alias,
    EnumMetadata,
    FixFieldValue,
    FixMetadata,
    IcebergMetadata,
    ProtocolMetadata,
    canonical_versions,
    encoded_key,
    encodings_of,
    newest_of,
    newest_rank,
    version_rank,
)
from rekep.fields.names import column_name, column_names, display_name

__all__ = [
    "display_name",
    "column_name",
    "column_names",
    "ANY_VERSION",
    "Alias",
    "BinaryField",
    "ClassBuilder",
    "DESCRIPTION",
    "DISPLAY",
    "DictionaryField",
    "ENUM",
    "EnumMetadata",
    "FIELD_ID",
    "FIX",
    "Field",
    "FieldBuilder",
    "FixFieldValue",
    "FixMetadata",
    "FixedSizeListField",
    "ICEBERG",
    "ITEM",
    "IcebergMetadata",
    "LargeListField",
    "LargeListViewField",
    "ListField",
    "ListViewField",
    "MapField",
    "NAME",
    "NAMESPACE",
    "PARTITION_KEY",
    "PRIMARY_KEY",
    "ProtocolMetadata",
    "SORT_KEY",
    "SORT_ORDER",
    "StructField",
    "TimestampField",
    "canonical_versions",
    "cast_batch",
    "cast_reader",
    "cast_table",
    "encoded_key",
    "encodings_of",
    "merge_fields",
    "merge_schemas",
    "newest_of",
    "newest_rank",
    "scalar",
    "version_rank",
]
