"""The Airflow service: DAG modules as a deployable resource.

Same shape as the Iceberg and Doris stacks -- a resource with idempotent
verbs and a dependency-ordered deploy -- but what Airflow consumes is
*files*: one generated Python module per job in its dags folder. So the
resource here is `Dags`, `get_or_create` compares rendered content, and
`deploy` converges a folder of side files into a folder of DAG modules.
Nothing imports Airflow itself: rendering is strings, and the generated
module does the real import inside the scheduler.
"""

from __future__ import annotations

import logging
import os
import pathlib

from rekep.job import Job, load_all

__all__ = ["Airflow", "Dags"]

logger = logging.getLogger("rekep.airflow")

#: What one generated DAG module contains. The scheduler imports it; the side
#: file stays the single source, loaded and built fresh at parse time.
MODULE = '''"""Generated by rekep -- edit the side file, not this module."""

from rekep.airflow.jobs import build
from rekep.job import load

globals()["{name}"] = build(load(r"{side_file}"))
'''


class Dags:
    """The deployable DAG modules a jobs folder declares."""

    def __init__(self, root: str | os.PathLike[str] | None = None) -> None:
        self.root = pathlib.Path(root)

    def list(self) -> list[Job]:
        """Every declared job -- each becomes exactly one Airflow DAG."""
        return load_all(self.root)

    def side_file(self, job: Job) -> pathlib.Path:
        """The side file a job was declared in, matched by name."""
        for path in sorted(self.root.glob("*")):
            if path.stem == job.name:
                return path
        raise FileNotFoundError(f"no side file for job {job.name!r} under {self.root}")

    def render(self, job: Job) -> str:
        """The Python module Airflow will import for this job."""
        return MODULE.format(name=job.name, side_file=self.side_file(job).resolve())

    def get_or_create(
        self, job: Job, dags_folder: pathlib.Path, dry_run: bool = False
    ) -> pathlib.Path:
        """Write the job's module; identical content is a logged no-op."""
        target = dags_folder / f"{job.name}.py"
        rendered = self.render(job)
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            logger.info("job %s: module up to date, nothing to do", job.name)
            return target
        verb = "would write" if dry_run else "write"
        logger.info("job %s: %s %s", job.name, verb, target)
        if not dry_run:
            dags_folder.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8", newline="\n")
        return target

    def delete(self, job: Job, dags_folder: pathlib.Path, dry_run: bool = False) -> None:
        target = dags_folder / f"{job.name}.py"
        if not target.exists():
            logger.info("job %s: no module, nothing to do", job.name)
            return
        logger.info("job %s: %s %s", job.name, "would remove" if dry_run else "remove", target)
        if not dry_run:
            target.unlink()


class Airflow:
    """One deployment's Airflow stack: the dags resource and its deploy."""

    def __init__(self, root: str | os.PathLike[str] | None = None) -> None:
        self.dags = Dags(root)

    @classmethod
    def deploy_folder(
        cls,
        root: str | os.PathLike[str] | None = None,
        *,
        dags_folder: str | os.PathLike[str],
        dry_run: bool = False,
    ) -> list[str]:
        """Converge every declared job into `dags_folder`, one call."""
        return cls(root).deploy(dags_folder, dry_run=dry_run)

    def deploy(self, dags_folder: str | os.PathLike[str], dry_run: bool = False) -> list[str]:
        """All dag modules, written or confirmed current, name order."""
        folder = pathlib.Path(dags_folder)
        deployed = [
            self.dags.get_or_create(job, folder, dry_run=dry_run).name for job in self.dags.list()
        ]
        logger.info("deploy complete: %d dag module(s)", len(deployed))
        return deployed
