"""The Airflow service: DAG modules as a deployable resource.

Same shape as the Iceberg and Doris stacks -- a resource with idempotent
verbs and a dependency-ordered deploy -- but what Airflow consumes is
*files*: one generated Python module per `rekep.dag.Dag` in its dags folder.
So the resource here is `Dags`, `get_or_create` compares rendered content,
and `deploy` converges a folder of side files into a folder of DAG modules.
Nothing imports Airflow itself: rendering is strings, and the generated
module does the real import inside the scheduler.
"""

from __future__ import annotations

import logging
import os
import pathlib

from rekep import config
from rekep.dag import EXTENSIONS, Dag, load

__all__ = ["Airflow", "Dags"]

logger = logging.getLogger("rekep.airflow")

#: What one generated DAG module contains. The scheduler imports it; the side
#: file stays the single source, loaded and built fresh at parse time.
MODULE = '''"""Generated by rekep -- edit the side file, not this module."""

from rekep.dag import load

globals()["{name}"] = load(r"{side_file}").into_airflow()
'''


class Dags:
    """The deployable DAG modules a dags folder declares."""

    def __init__(self, root: str | os.PathLike[str] | None = None) -> None:
        self.root = pathlib.Path(root) if root is not None else None

    def entries(self) -> list[tuple[pathlib.Path, Dag]]:
        """Every declared dag, with the side file it came from.

        The path is carried rather than looked up again from the dag: a dag
        that renders its identity from the git branch has a `dag_id` its file
        stem deliberately does not match, and a module that guessed would
        stop deploying exactly on the branches that need it most.
        """
        folder = config.folder("dags", self.root)
        return [
            (path, config.register(load(path)))
            for path in sorted(folder.glob("*"))
            if path.suffix in EXTENSIONS
        ]

    def list(self) -> list[Dag]:
        """Every declared dag -- each becomes exactly one Airflow DAG."""
        return [dag for _, dag in self.entries()]

    def render(self, path: pathlib.Path, dag: Dag) -> str:
        """The Python module Airflow will import for the dag `path` declares."""
        return MODULE.format(name=dag.dag_id(), side_file=pathlib.Path(path).resolve())

    def get_or_create(
        self, path: pathlib.Path, dag: Dag, dags_folder: pathlib.Path, dry_run: bool = False
    ) -> pathlib.Path:
        """Write the dag's module; identical content is a logged no-op."""
        target = dags_folder / f"{dag.dag_id()}.py"
        rendered = self.render(path, dag)
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            logger.info("dag %s: module up to date, nothing to do", dag.dag_id())
            return target
        verb = "would write" if dry_run else "write"
        logger.info("dag %s: %s %s", dag.dag_id(), verb, target)
        if not dry_run:
            dags_folder.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8", newline="\n")
        return target

    def delete(self, dag: Dag, dags_folder: pathlib.Path, dry_run: bool = False) -> None:
        target = dags_folder / f"{dag.dag_id()}.py"
        if not target.exists():
            logger.info("dag %s: no module, nothing to do", dag.dag_id())
            return
        logger.info("dag %s: %s %s", dag.dag_id(), "would remove" if dry_run else "remove", target)
        if not dry_run:
            target.unlink()


class Airflow:
    """One deployment's Airflow stack: the dags resource and its deploy."""

    def __init__(self, root: str | os.PathLike[str] | None = None) -> None:
        self.dags = Dags(root)

    @classmethod
    def deploy_folder(
        cls,
        root: str | os.PathLike[str] | None = None,
        *,
        dags_folder: str | os.PathLike[str],
        dry_run: bool = False,
    ) -> list[str]:
        """Converge every declared dag into `dags_folder`, one call."""
        return cls(root).deploy(dags_folder, dry_run=dry_run)

    def deploy(self, dags_folder: str | os.PathLike[str], dry_run: bool = False) -> list[str]:
        """All dag modules, written or confirmed current, name order."""
        folder = pathlib.Path(dags_folder)
        deployed = [
            self.dags.get_or_create(path, dag, folder, dry_run=dry_run).name
            for path, dag in self.dags.entries()
        ]
        logger.info("deploy complete: %d dag module(s)", len(deployed))
        return deployed
