name: flatten_executions
notebook: flatten_executions.ipynb
parameters:
  source: market.books
  target: market.executions
  start: null
  end: null
  catalog: rekep
  catalog_properties:
    type: sql
    uri: sqlite:///data/catalog.db
    warehouse: file://data/warehouse
  merge_by: true
  commit_row_size: 250000
