name: parse_market
notebook: parse_market.ipynb
parameters:
  source: logs.market
  target: market.books
  start: null
  end: null
  catalog: rekep
  catalog_properties:
    type: sql
    uri: sqlite:///data/catalog.db
    warehouse: file://data/warehouse
  snapshot_every: 3600000000000
  max_lateness_ns: 900000000000
  max_order_age_ns: 86400000000000
  max_side_alive: 10000
  merge_by: true
  commit_row_size: 250000
