"""The pipeline pages show the fixture's own rows, and the rows stay the run's."""

from __future__ import annotations

import datetime
import decimal
import importlib.util
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any

import pyarrow
import pytest

ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools" / "pipeline_samples.py"
SAMPLES = ROOT / "docs" / "pipeline" / "tasks" / "samples"
PAGES = ("parse-messages", "parse-fix-bronze", "parse-fix-silver", "build-dbt")
UTC = datetime.timezone.utc


def _tool() -> Any:
    specification = importlib.util.spec_from_file_location("rekep_pipeline_samples_tool", TOOL)
    assert specification is not None and specification.loader is not None
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


def test_each_task_page_includes_its_own_sample() -> None:
    """A page carries the include line for its own generated sample."""
    tool = _tool()
    assert tool.PAGES == PAGES
    for page in PAGES:
        source = (ROOT / "docs" / "pipeline" / "tasks" / f"{page}.md").read_text(encoding="utf-8")
        assert f'--8<-- "docs/pipeline/tasks/samples/{page}.md"' in source, page
        sample = (SAMPLES / f"{page}.md").read_text(encoding="utf-8")
        assert sample.startswith("<!-- Generated by tools/pipeline_samples.py"), page
        if page == "parse-messages":
            assert "| `rownum` |" in sample, page
        else:
            assert "| `rownum` |" not in sample, page
        if page == "build-dbt":
            assert "| `eventkey` |" in sample, page
        # The page reads the tables rather than pasting them, so the rendered
        # rows appear once, in the file the page includes.
        shown = (ROOT / "docs" / "pipeline" / "tasks" / f"{page}.md").read_text(encoding="utf-8")
        assert "| `rownum` |" not in shown, page


def test_a_cell_is_rendered_the_way_a_reader_compares_it() -> None:
    tool = _tool()
    key = uuid.UUID("01a0004f6a7f7000b6152bc2612bd752")

    assert tool.cell(None) == ""
    assert tool.cell(datetime.datetime(2026, 8, 14, 12, 46, 39, 743000, tzinfo=UTC)) == (
        "2026-08-14 12:46:39.743"
    )
    assert tool.cell(datetime.datetime(2026, 8, 14, 12, 46, 39, 743016, tzinfo=UTC)) == (
        "2026-08-14 12:46:39.743016"
    )
    assert tool.cell(decimal.Decimal("600.000000000000000000")) == "600"
    assert tool.cell(decimal.Decimal("83.080000000000000000")) == "83.08"
    assert tool.cell(decimal.Decimal("0E-18")) == "0"
    assert tool.cell(key.bytes) == "…612bd752"
    assert tool.cell([key.bytes, key.bytes]) == "2"
    assert tool.cell("8=FIX.4.4|35=8") == "8=FIX.4.4\\|35=8"
    assert tool.cell(b"ABBN.S") == "ABBN.S"


def test_the_prose_of_a_line_is_what_follows_its_header() -> None:
    tool = _tool()
    line = (
        b"2026-08-14 14:46:39.769 [15255-e7254b12:9f03166699:40218] [X] (INFO) "
        b"Receiving : 8=FIX.4.4|9=938"
    )

    assert tool.prose(line, width=24) == "Receiving : 8=FIX.4.4\\|9=…"
    assert tool.prose(b"no header here", width=64) == "no header here"


def test_the_walk_order_is_the_one_the_table_declares() -> None:
    """`currunix, seqnum, curruuid`, and an unnumbered head after its own steps."""
    tool = _tool()
    instant = datetime.datetime(2026, 8, 14, 12, 46, 39, 743000, tzinfo=UTC)
    later = instant + datetime.timedelta(milliseconds=18)
    chain = pyarrow.table(
        {
            "currunix": pyarrow.array(
                [instant, instant, later, instant], pyarrow.timestamp("us", "UTC")
            ),
            "seqnum": pyarrow.array([2, None, None, 1], pyarrow.int64()),
            "curruuid": pyarrow.array(
                [b"b" * 16, b"a" * 16, b"c" * 16, b"d" * 16], pyarrow.binary(16)
            ),
        }
    )

    ordered = tool.walked(chain)

    assert ordered.column("curruuid").to_pylist() == [b"d" * 16, b"b" * 16, b"a" * 16, b"c" * 16]
    assert ordered.column_names == chain.column_names


@pytest.mark.integration
def test_the_published_samples_are_what_a_run_lands() -> None:
    """The four tasks over the fixture render exactly the files the pages include."""
    checked = subprocess.run(  # noqa: S603
        [sys.executable, str(TOOL), "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert checked.returncode == 0, checked.stdout + checked.stderr
    assert "4 samples match" in checked.stdout
